//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmaPlayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmaPlayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info: .
        /// </summary>
        public static string About1 {
            get {
                return ResourceManager.GetString("About1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Link.
        /// </summary>
        public static string About2 {
            get {
                return ResourceManager.GetString("About2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Credit.
        /// </summary>
        public static string CreditSkip {
            get {
                return ResourceManager.GetString("CreditSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Default 1, Max 1000).
        /// </summary>
        public static string HiddenDesc {
            get {
                return ResourceManager.GetString("HiddenDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden Probability.
        /// </summary>
        public static string HiddenProb {
            get {
                return ResourceManager.GetString("HiddenProb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string isRandom {
            get {
                return ResourceManager.GetString("isRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L←.
        /// </summary>
        public static string L {
            get {
                return ResourceManager.GetString("L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder....
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R→.
        /// </summary>
        public static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice.
        /// </summary>
        public static string SelectStone {
            get {
                return ResourceManager.GetString("SelectStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone1.
        /// </summary>
        public static string Stone1 {
            get {
                return ResourceManager.GetString("Stone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone2.
        /// </summary>
        public static string Stone2 {
            get {
                return ResourceManager.GetString("Stone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone3.
        /// </summary>
        public static string Stone3 {
            get {
                return ResourceManager.GetString("Stone3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Stone.
        /// </summary>
        public static string StoneSkip {
            get {
                return ResourceManager.GetString("StoneSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmaPlayer.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
